[build]
#build-std = false                              # do not build the std library. has precedence over xargo
#xargo = true                                   # enable the use of xargo by default                                    # do not use zig cc for the builds
default-target = "x86_64-unknown-linux-gnu"    # use this target if none is explicitly provided

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
]

[target.x86_64-pc-windows-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update"
]