services:
  grafana:
    user: root
    container_name: 'ibumblebee-alert4ml-datasource'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.3-ubuntu}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/ibumblebee-alert4ml-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/ibumblebee-alert4ml-datasource
      - ./data/grafana/grafana.db:/var/lib/grafana/grafana.db
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.ibumblebee-alert4ml-datasource:debug
      GF_LOG_LEVEL: error
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: ibumblebee-alert4ml-datasource
