[package]
name = "rsod"
version = "0.1.1"
edition = "2021"

[dependencies]
rsod-outlier = { workspace = true }
rsod-forecaster = { workspace = true }
rsod-baseline = { workspace = true }
rsod-storage = { workspace = true }
rsod-utils = { workspace = true }

[lints]
workspace = true