name: "Grafana Build Plugin"
description: "Builds a Grafana plugin"

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'x86_64-unknown-linux-gnu'
          # - 'aarch64-unknown-linux-gnu'
          # - 'aarch64-apple-darwin'
          # - 'x86_64-pc-windows-gnu'
          # - 'aarch64-pc-windows-gnu'
    steps:
      - uses: actions/checkout@v4

      - name: Run Rust Builder
        uses: ./.github/actions/rust-builder
        with:
          target: ${{ matrix.target }}

      - uses: grafana/plugin-actions/build-plugin@main
        with:
          # refer to https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token to generate it
          # save the value in your repository secrets
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          # creates a signed build provenance attestation to verify the authenticity of the plugin build
          attestation: true
          use_changelog_generator: true
          go-version: '1.25'
          node-version: '22'
  
      - name: Package Plugin
        uses: grafana/plugin-actions/package-plugin@main
