# filepath: .github/workflows/actions/rust-builder/rust.yml
name: 'Rust Plugin Builder'
description: 'Compiles Rust backend for the plugin'

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'x86_64-unknown-linux-gnu'
          # - 'aarch64-unknown-linux-gnu'
          # - 'aarch64-apple-darwin'
          # - 'x86_64-pc-windows-gnu'
          # - 'aarch64-pc-windows-gnu'
    steps:
      - uses: actions/checkout@v4

      # - uses: grafana/plugin-actions/build-plugin@main
      #   with:
      #     # refer to https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token to generate it
      #     # save the value in your repository secrets
      #     policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
      #     # creates a signed build provenance attestation to verify the authenticity of the plugin build
      #     attestation: true
      #     use_changelog_generator: true
  
      # 执行自定义 Rust 逻辑
      - name: Run Custom Rust Logic
        uses: ./.github/actions/rust-builder
        with:
          target: ${{ matrix.target }}

      # # 3. 只调用官方的打包步骤
      # - name: Package Plugin
      #   uses: grafana/plugin-actions/package-plugin@main
